package me.chat.plugin.commands;

import org.bukkit.Bukkit;
import org.bukkit.Sound;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import ru.tehkode.permissions.bukkit.PermissionsEx;

public class CC implements CommandExecutor{

	@Override
	public boolean onCommand(CommandSender sender, Command cmd, String lable, String[] args) {
		
		Player p = (Player)sender;
		if(p.hasPermission("md.core.cc")) {
			p.playSound(p.getLocation(), Sound.ANVIL_USE, 100.f, 100.f);
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§8┃");
				Bukkit.broadcastMessage("§c§l[⚠] CLEARCHAT §7Chat has been cleared by "+String.valueOf(PermissionsEx.getUser(p).getSuffix()).replace("&", "§")+p.getName());
		}else{
			p.sendMessage("§c§l[§4§lℹ§c§l] ERROR §7You do not have enough permissions.");
		}
		
		return false;
	}

}
